sudo: false
language: python
cache: pip

matrix:
  include:
    - env: TOXENV=lint
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.4
      env: TOXENV=py34-django111
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.4
      env: TOXENV=py34-django20
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django20

install:
  - pip install tox
  - if [ $TOXENV != lint ]; then pip install coveralls; fi
script:
  - tox
  - if [ $TOXENV != lint ]; then coverage report -m; fi
after_success:
  - if [ $TOXENV != lint ]; then coveralls --verbose; fi
