language: python
python:
  - "2.6"
  - "2.7"
env:
#  - DJANGO=1.3.4
  - DJANGO=1.5
#  - DJANGO=https://github.com/django/django/zipball/master
install:
#  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r schedule/requirements.txt --use-mirrors
  - pip install -e . --use-mirrors

before_script:
    - pip install python-coveralls coverage
script:
  - coverage run runtests.py

after_success:
  # Submit data from .coverage to coveralls on success
  - coveralls
