language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - pip install . --use-mirrors
    - pip install -r schedule/requirements.txt --use-mirrors

script: python schedule/manage.py syncdb
script: python schedule/manage.py test

env:
    - DJANGO=1.5
