language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.8
      env: TOXENV=py36-django30
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.8
      env: TOXENV=py38-djangomain
    - python: 3.9
      env: TOXENV=py39-djangomain
  allow_failures:
    - env: TOXENV=py38-djangomain
    - env: TOXENV=py39-djangomain

install:
  - pip install tox
  - if [ $TOXENV != lint ]; then pip install coveralls; fi
script:
  - tox
  - if [ $TOXENV != lint ]; then coverage report -m; fi
after_success:
  - if [ $TOXENV != lint ]; then coveralls --verbose; fi
