language: python
python:
  - "2.6"
  - "2.7"
env:
#  - DJANGO=1.3.4
  - DJANGO=1.5
#  - DJANGO=https://github.com/django/django/zipball/master
install:
#  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -e . --use-mirrors
  - pip install -r schedule/requirements.txt --use-mirrors
script:
  - python schedule/manage.py syncdb
  - python schedule/mange.py test

