language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.7.1
install:
  - pip install -e . --use-mirrors
  - pip install -r schedule/requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - python setup.py develop
  - python schedule/manage.py migrate
  - python schedule/manage.py loaddata schedule
  - python schedule/manage.py test
  - coverage report -m
after_success:
  - coveralls --verbose
